### ISSUE TITLE
Users with no searchprovider* Django permissions

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#75]
In the Django Admin page, create a User group with all result* and search* permissions but no searchprovider* permissions. Or, remove the "Can view search provider" from an existing User group.

Verify that the SearchProviders list is 403 Forbidden, as it should be.

Run a new search, and you will get results.

The bug is that you should be able to create/send a search but not get search results back since SearchProviders should completely be unavailable to the User due to the Django permissions setup.

**Comment by sidprobstein** [comment]
Resolved in 1.8

**Comment by erikspears** [comment]
Rechecking with latest 1.8 ... does not appear to be fixed.

Verified that Search Provider List is not visible (returns a 403) to a User account without the "Can view search provider" permission, as before.  See here:
![Issue 75 - Search providers 403](https://user-images.githubusercontent.com/98238295/212758495-625e0cf1-96c0-488f-8a4b-19721a518ced.png)

However, searches by the User still return results.  See here:
![Issue 75 - example resutls](https://user-images.githubusercontent.com/98238295/212758528-29fe27de-c91b-4f72-bcfa-f956a7d4fa61.png)

Django admin permissions for the `Users` Group my test user `Tron` is part of:
![Issue 75 - Group permissions](https://user-images.githubusercontent.com/98238295/212758548-ad8a1eb7-2f30-4590-980b-f438304978cf.png)

CC:  @sidprobstein , reassigning to you for now.

**Comment by sshadmand** [comment]
Hey all, I ran compose (using podman) stood up well. When running search I get the same issue. Before I go in to the container, I wanted to see if any progress on having the OTB working as expected. Thanks!

**Comment by sidprobstein** [comment]
Hi @sshadmand thank you for reporting! I am looking at it now.

**Comment by sidprobstein** [comment]
Definitely not fixed, but will be. This requires a little testing so won't be until tomorrow. 
Workaround: remove the `swirl.add_search` permission.

**Comment by sidprobstein** [comment]
Fixed in main. 

Should a user create a Search object that has status NEW_SEARCH, and not have the permission `swirl.view_searchproviders`, the object will be created, but have the status `ERR_NEED_PERMISSION`.

**Comment by erikspears** [comment]
Validated the fix in latest `main` update of 1.8.2, looks good!

For a User without any searchprovider* permissions, searches are not resolved.

The Results List page returns:
```
HTTP 503 Service Unavailable
```
<img width="266" alt="Result list 503" src="https://user-images.githubusercontent.com/98238295/216461534-6fa682c8-1943-4dbe-b8cf-8ee66736c126.png">

The SearchProviders page returns:
```
HTTP 403 Forbidden
```
<img width="345" alt="SearchProvider 503" src="https://user-images.githubusercontent.com/98238295/216461980-f95f15a8-2de0-4263-b6ef-55285a6105d6.png">

The Search List page returns the error noted by @sidprobstein in the fix comment above:
```
        "status": "ERR_NEED_PERMISSION",
```
<img width="655" alt="Search list 503" src="https://user-images.githubusercontent.com/98238295/216462188-eac8eece-608b-42d2-973b-780f77736e9a.png">


And the celery-worker.log has this corresponding entry:
```
[2023-02-02 17:11:48,040: WARNING/ForkPoolWorker-8] User tron needs permission view_searchprovider
```

Users WITH the correct seachprovider* permission can search and view results (and SearchProviders) as expected.  The default Admin user continues to work as expected as well.

**Comment by erikspears** [comment]
Validate the fix in the latest Docker build as well, looks good!  Same steps and outcome as local SWIRL testing in the prior comment.

**Comment by sshadmand** [comment]
@sidprobstein thanks for the fix and response :-)
