### ISSUE TITLE
Highlighting issue:  title term with adjacent punctuation

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#77]
A search that included the term tesla yielded the title match below; however hit highlighting was not applied to the title match next to the question mark.

Hit title:  Where is shipping's Elon Musk and Tesla?

Note missing highlighting in title below:
<img width="1258" alt="Screenshot 2022-12-17 at 5 57 06 PM" src="https://user-images.githubusercontent.com/98238295/208269007-7636e537-8193-436f-be40-4f8b0cd670bb.png">

**Comment by sidprobstein** [comment]
This is resolved in 1.8

**Comment by erikspears** [comment]
Retesting with the latest 1.8 ... does not appear to be fixed.

Search term:  `mastodon`

Results below - note the bug still present in the title of the 1st hit (no highlighting of the search term next to the `?` character).  Fo comparison, the 3rd hits highlights the title match correctly (no adjacent punctuation).
![Issue 77 - results](https://user-images.githubusercontent.com/98238295/212759646-502313bb-5f0c-4ad3-9b75-767e4e6fbe13.png)

CC:  @sidprobstein , reassigning to you for now.

**Comment by erikspears** [comment]
During v. 1.9.x testing, we have seen some additional examples of this Issue.  Perhaps these will help shed some light on the what's happening with this behavior.
For the query:  `q=strategic technology consulting`

Notice that the word `Consulting` in the 1st result is not highlighted, presumably because there is no space between it and the vertical pipe next to it.  While in the 2nd hit, the same word IS highlighted correctly perhaps since there is a space between it and the vertical pipe that follows.

![Issue 77 - pipe example](https://user-images.githubusercontent.com/98238295/220647422-519a719b-4d67-4853-b66c-e0d116c25758.png)

Another interesting example from the same results (so, same query) ... Notice that the ampersand in this title (perhaps a typo or other ingestion issue) prevents a match from being highlighted:

![Issue 77 - ampersand](https://user-images.githubusercontent.com/98238295/220649709-1600d2cd-7cd2-4c15-a93a-65018e41c193.png)

One final example from the same result list ... Notice in this hit that two colons are highlighted along with their matching terms:

![Issue 77 - colons](https://user-images.githubusercontent.com/98238295/220650590-cae57e97-7b8d-407b-85fa-f37bd30eb189.png)

**Comment by sidprobstein** [comment]
Not all of these are fixed in 1.10, but the first two examples are for sure.

**Comment by erikspears** [comment]
Per @sid-swirl , improvements coming in 1.10 for this!  The first few example cases above will be addressed for sure, and we'll keep an eye out for any similar issues.

**Comment by ryandeisma** [comment]
@sid-swirl This issue looks a lot better with recent changes. Hit tags are now present in almost all locations that were previously not covered. During testing, noticed one area where words ending in an apostrophe are being caught and added to the Hit's list, however, they are not tagged in their location. Attached is a screenshot that should tag the words prince and player. "Player's" in the title appears in the Hit list, but is not surrounded by an <em>  tag. 
<img width="930" alt="Screenshot 2023-03-21 at 7 20 58 PM" src="https://user-images.githubusercontent.com/27780793/226766485-4755d76e-9db3-459b-8633-a76c7ea84dc6.png">

**Comment by ryandeisma** [comment]
Highlighting in Title and Body now has tags. Still open bugs being tracked in other cards related to highlighting, but the specific issue of tags around punctuation in title and body has been resolved for upcoming 1.10 release.

**Comment by ryandeisma** [comment]
Highlighting in Title and Body now has tags. Still open bugs being tracked in other cards related to highlighting, but the specific issue of tags around punctuation in title and body has been resolved for upcoming 1.10 release.
