### ISSUE TITLE
v. 1.8 - Cannot add PostgreSQL SearchProvider:  "\"PostgreSQL\" is not a valid choice."

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#88]
Attempting to validate the Postgres funding example from the Developer's Guide, encountered an error attempting to add the corresponding SearchProvider:  `HTTP 400 Bad Request`

Most direct way to reproduce is try adding the Postgres funding db example SearchProvider:  `funding_db_postgres.json`
...available here in 1.8:  https://github.com/sidprobstein/swirl-search/blob/main/SearchProviders/funding_db_postgres.json

Copy/paste this json into the Raw Data tab of the Search Provider List page: http://localhost:8000/swirl/searchproviders/

Both with and without updates to the `"url:"` line of the SP, SWIRL returns the 404 above:
![Postgres connector invalid](https://user-images.githubusercontent.com/98238295/212558561-4d436903-cdaf-4093-9127-b58b22d20efc.png)

Behavior confirmed in:
- MacOS installation -- SWIRL 1.8
- Docker installation -- SWIRL 1.8

**Comment by erikspears** [comment]
Issue persists after a `git pull` to update Swirl 1.8 on the Mac a few minutes ago.  Seeing this in the `django.log`:
```
Forbidden: /swirl/searchproviders/
2023-01-15 15:15:02,615 WARNING  Forbidden: /swirl/searchproviders/
Forbidden: /swirl/search/
2023-01-15 15:15:03,181 WARNING  Forbidden: /swirl/search/
2023-01-15 15:15:03,713 WARNING  User AnonymousUser needs permissions view_search(False), view_result(False)
Forbidden: /swirl/results/
2023-01-15 15:15:03,737 WARNING  Forbidden: /swirl/results/
2023-01-15 15:15:13,821 INFO     views.py: Search.list()!
Bad Request: /swirl/searchproviders/
2023-01-15 15:16:01,586 WARNING  Bad Request: /swirl/searchproviders/
```
And the `celery-worker.log` has mention of a DEBUG setting potentially being enabled?  Not sure if that's the case or if it's even related, but here's at least part of the message:
```
[2023-01-15 15:10:28,404: WARNING/MainProcess] /Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
```

**Comment by sidprobstein** [comment]
This is resolved in documentation: see https://github.com/sidprobstein/swirl-search/wiki/3.-Developer-Guide#installing-the-postgresql-driver for details

**Comment by erikspears** [comment]
Retesting documentation instructions with latest 1.8 ... fixed!

Able to successfully create the Postgres Search Provider after following the updated steps in the Developer Guide:
![Issue 88 - Saerch Provider success](https://user-images.githubusercontent.com/98238295/212761144-d04cf5c1-4f83-4602-9297-b6e7bcbd77cd.png)

And, the funding example outlined in the docs now returns results as expected from this Search Provider:
![Issue 88 - Results success](https://user-images.githubusercontent.com/98238295/212761597-bae1f279-d712-4ad1-b78d-3cb3df64cdff.png)

Thanks, @sidprobstein !

**Comment by erikspears** [comment]
FYI:  all worked as expected in MacOS.  In Docker, got the SP added, but the error in Issue 69 still appears.  Reopened that ticket.
